### ISSUE TITLE
Java-debug-adapter install failed

### ISSUE THREAD

**Issue by chasing-freedom** [simaxme/java.nvim#2]
**Nvim version:** `NVIM v0.10.0-dev-1991+gdd00b6b44`

Mason log
>     Downloading file "https://open-vsx.org/api/vscjava/vscode-java-debug/0.52.0/file/vscjava.vscode-java-debug-0.52.0.vsix"…
>         Unpacking "vscjava.vscode-java-debug-0.52.0.vsix"…
>         Archive:  vscjava.vscode-java-debug-0.52.0.vsix
>           inflating: ./extension.vsixmanifest  
>           inflating: ./[Content_Types].xml   
>           inflating: ./extension/CHANGELOG.md  
>           inflating: ./extension/Configuration.md  
>           inflating: ./extension/dist/164.js  
>           inflating: ./extension/dist/488.js  
>           inflating: ./extension/dist/939.js  
>           inflating: ./extension/dist/939.js.LICENSE.txt  
>           inflating: ./extension/dist/extension.js  
>           inflating: ./extension/dist/extension.js.LICENSE.txt  
>           inflating: ./extension/images/commands/hot_code_replace.svg  
>           inflating: ./extension/LICENSE.txt  
>           inflating: ./extension/logo.png    
>           inflating: ./extension/package.json  
>           inflating: ./extension/package.nls.es.json  
>           inflating: ./extension/package.nls.it.json  
>           inflating: ./extension/package.nls.json  
>           inflating: ./extension/package.nls.zh-cn.json  
>           inflating: ./extension/package.nls.zh-tw.json  
>           inflating: ./extension/README.md   
>           inflating: ./extension/SECURITY.md  
>           inflating: ./extension/server/com.microsoft.java.debug.plugin-0.47.0.jar  
>           inflating: ./extension/ThirdPartyNotices.txt  
>           inflating: ./extension/Troubleshooting_encoding.md  
>           inflating: ./extension/Troubleshooting.md  
>         Link target "/home/(my_username)/.local/share/nvim/mason/packages/java-debug-adapter/extension/server/com.microsoft.java.debug.plugin-0.50.0.jar" does not exist.

maybe link to the old version?

**Comment by simaxme** [comment]
Hello, 
unfortunately, I can not help you with this issue. This repository does not implement anything regarding LSP and mainly contains utilities for java development. 
You may need to create an issue in [mason-registry](https://github.com/mason-org/mason-registry). The file you are refering to is [java-debug-adapter/package.yaml](https://github.com/mason-org/mason-registry/blob/main/packages/java-debug-adapter/package.yaml).
Because I cannot help you any further, I will close this issue.
