### ISSUE TITLE
Renamed file via nvim-tree, package names and imports didn't change

### ISSUE THREAD

**Issue by imbacraft** [simaxme/java.nvim#3]
Hello @simaxme and thank you for creating this plugin.

I fillowed your instructions, but the plugin seems not to work.

This is how I installed it:

```lua
  {
    'simaxme/java.nvim',
    dependencies = {
      "nvim-tree/nvim-tree.lua",
    },
    config = function()
      require("java").setup()
    end
  },

```

I then went to nvim-tree, press r on a package or a class ---> renaming happens, but imports and packges are not updated.

I suspect that there is a conflict with [nvim-java](https://github.com/nvim-java/nvim-java), maybe because of the same plugin name?

How can I help debug this?

**Comment by simaxme** [comment]
Hello,
i just released an update that allows you to use `simaxme-java` instead of `java` as a package name. This should avoid the compatibility issues.
Hope my plugin works now :D

**Comment by imbacraft** [comment]
@simaxme Thank you for the update.

Using the new name, rename a class file name worked nicely from nvim-tree with "r".

However, renaming a package did not update the package names in the other classes.
Also, moving a class from one package to the other did not update the package imports.

It might be because I am using both [nvim-java](https://github.com/nvim-java/nvim-java) and [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls).

My config if you want to check this out is : [dusk.nvim](https://github.com/imbacraft/dusk.nvim)

**Comment by simaxme** [comment]
> However, renaming a package did not update the package names in the other classes.

I did not consider this and forgot that package renaming is also important, i will try to add this feature today. 

> Also, moving a class from one package to the other did not update the package imports.

May I ask how you have moved the class? If you are using `r` and renaming the file with relative path names, it should work. 
For instance:
`../MyServiceName.java`
If you are using any other method, I can try to listen to the corresponding event.

**Comment by imbacraft** [comment]
@simaxme Thank you for the prompt response.

Renaming packages is essential, so I look forward to the update.

I moved the class by going to nvim-tree, pressing "x" (cut) on the class and "p" on the package I want to move it to.

I can confirm also that renaming the file and using "../classname.java" works, but it doesn't seem optimal to me. The previous method seems natural.

**Comment by simaxme** [comment]
@imbacraft 
I just finished the update. You should now be able to rename packages. 
It seems like nvim-tree will always send a `NodeRenamed` event when using "x" and "p". Therefore, it should work automatically. I have just tested using it and it worked without changing anything. 
Maybe you have some different key mapping with "x" and "p"?

**Comment by imbacraft** [comment]
@simaxme I just tested everything, it works smoothly.

Thank you for this much needed plugin, this issue can be considered resolved.

**Comment by simaxme** [comment]
No problem 🙃
